CREATE DATABASE IF NOT EXISTS ${DB_NAME}
  DEFAULT CHARACTER SET = 'utf8'
  DEFAULT COLLATE = 'utf8_general_ci';

CREATE USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS ${DB_NAME}.pages
(
  id      INT(11) UNSIGNED AUTO_INCREMENT,
  slug    VARCHAR(255) NOT NULL,
  tittle  VARCHAR(255) NOT NULL,
  content TEXT         NULL,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX page_slug ON ${DB_NAME}.pages (slug);
